.pragma library

// Generated by tools/emoji/generate.py from third_party/emoji/ (Emoji 16.0, CLDR 46) — do not edit by hand.
//
// Every fully-qualified sequence of Emoji 16.0, in emoji-test.txt order,
// named by that file's own comments with CLDR 46's English annotations as
// fallback; regeneration is offline and byte-deterministic. A sequence
// whose trailing skin-tone modifiers strip to another kept entry (kept
// entries are compared without U+FE0F) is that entry's variant and is
// hoisted to follow it: the variant's `base` is the base's index and the
// base's `variants` lists its variants' indexes, with bases at -1.
// Variants carry no keywords in any language — search reaches them
// through their names. Besides the English keywords, each entry carries
// CLDR 46 Russian (`ru`) and Ukrainian (`uk`) keywords from that
// release's annotation files: search vocabulary only, display names stay
// English, and the entries that carry them are exactly the ones that
// carry English keywords. Groups follow emoji-test.txt; the ones with no
// fully-qualified entry are not here. Treat entries() and groups() as
// read-only; names and keywords are stored verbatim for display and
// lowercased once below for matching, so search is case-insensitive on
// both sides.

.import "EmojiCatalogData1.js" as Part1
.import "EmojiCatalogData2.js" as Part2
.import "EmojiCatalogData3.js" as Part3

var catalog = Part1.catalog.concat(Part2.catalog.concat(Part3.catalog))

var groupNames = [
    "Smileys & Emotion",
    "People & Body",
    "Animals & Nature",
    "Food & Drink",
    "Travel & Places",
    "Activities",
    "Objects",
    "Symbols",
    "Flags"
]

function entries() { return catalog }

function groups() { return groupNames }

// Matching text, lowercased once at load: names and keywords are stored
// verbatim above for display, and search must not depend on the case
// CLDR happens to publish ("flag: Ukraine", "CD", "Mrs.", "Дед Мороз").
var matchNames = []
var matchKeywords = []
var matchRu = []
var matchUk = []
for (var e = 0; e < catalog.length; e++) {
    matchNames.push(catalog[e].name.toLowerCase())
    matchKeywords.push(lowerAll(catalog[e].keywords))
    matchRu.push(lowerAll(catalog[e].ru))
    matchUk.push(lowerAll(catalog[e].uk))
}

function lowerAll(words) {
    var lowered = []
    for (var i = 0; i < words.length; i++) {
        lowered.push(words[i].toLowerCase())
    }
    return lowered
}

// Query terms are ANDed across name and keywords. A term earns the
// strongest tier any of its own matches reaches — the name or a name word
// leading with it, a keyword word leading with it, or merely a substring
// somewhere — and the entry ranks at the weakest of its terms' tiers;
// catalogue order breaks ties inside a tier. The ru and uk keyword lists
// join the keyword tier with the same numbers, but only for terms with a
// character beyond ASCII: CLDR ships the occasional Latin keyword in
// those lists ("100", "SUV"), and an English query's results must stay
// exactly what the English data alone yields. Every Cyrillic term is
// beyond ASCII by construction, so the added vocabulary stays fully
// reachable. limit caps the result; 0 or undefined means all.

function outsideAscii(term) {
    for (var i = 0; i < term.length; i++) {
        if (term.charCodeAt(i) > 127) return true
    }
    return false
}

function termTier(index, term, query, extended) {
    var name = matchNames[index]
    if (name === query) return 1
    var words = name.split(" ")
    for (var i = 0; i < words.length; i++) {
        if (words[i].indexOf(term) === 0) return 1
    }
    var keywordSets = extended
        ? [matchKeywords[index], matchRu[index], matchUk[index]]
        : [matchKeywords[index]]
    for (var s = 0; s < keywordSets.length; s++) {
        var keywords = keywordSets[s]
        for (var k = 0; k < keywords.length; k++) {
            var kw = keywords[k].split(" ")
            for (var j = 0; j < kw.length; j++) {
                if (kw[j].indexOf(term) === 0) return 2
            }
        }
    }
    if (name.indexOf(term) >= 0) return 3
    for (var m = 0; m < keywordSets.length; m++) {
        var substrings = keywordSets[m]
        for (var n = 0; n < substrings.length; n++) {
            if (substrings[n].indexOf(term) >= 0) return 3
        }
    }
    return 0
}

function search(query, limit) {
    var text = String(query === undefined || query === null ? "" : query).trim().toLowerCase()
    var terms = []
    var beyond = []
    var raw = text.split(/\s+/)
    for (var r = 0; r < raw.length; r++) {
        if (raw[r] !== "") {
            terms.push(raw[r])
            beyond.push(outsideAscii(raw[r]))
        }
    }
    if (terms.length === 0) return []
    var tiers = [[], [], []]
    for (var i = 0; i < catalog.length; i++) {
        var tier = 0
        for (var t = 0; t < terms.length; t++) {
            var earned = termTier(i, terms[t], text, beyond[t])
            if (earned === 0) { tier = 0; break }
            if (earned > tier) tier = earned
        }
        if (tier > 0) tiers[tier - 1].push(i)
    }
    var found = tiers[0].concat(tiers[1], tiers[2])
    var count = limit > 0 ? Math.min(limit, found.length) : found.length
    var results = []
    for (var n = 0; n < count; n++) results.push(catalog[found[n]])
    return results
}
