.pragma library

// The text-glyph shelf: the simple, classic glyphs — heart, smiling face,
// star — in the picker. These are BARE single BMP scalars — one
// character, one glyph, no sequences to split — delivered by the
// clipboard transaction like every pick. The generated catalogue cannot
// hold them by construction (it keeps only fully-qualified emoji
// sequences — the heart WITH its variation selector is there, the
// bare one is not), so this shelf is hand-curated and the generator
// never touches it. Entry shape is the catalogue's own (search,
// recents and usage work unchanged); no tone variants — a glyph has
// none. The suite pins the data contract: every entry is a lone BMP
// scalar — one character, no sequence.

var GROUP = "Text"

var glyphs = [
    { emoji: "\u2665", name: "heart suit",
      keywords: ["card", "heart", "love", "suit"], ru: ["любовь", "масть", "сердце", "червы"], uk: ["кохання", "масть", "серце", "чирва"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2661", name: "white heart suit",
      keywords: ["card", "heart", "love", "outline", "suit"], ru: ["любовь", "масть", "сердце", "контур"], uk: ["контур", "кохання", "серце"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2666", name: "diamond suit",
      keywords: ["card", "diamond", "suit"], ru: ["бубна", "масть"], uk: ["бубна", "масть"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2664", name: "white spade suit",
      keywords: ["card", "spade", "suit"], ru: ["масть", "пики"], uk: ["масть", "піки"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2660", name: "spade suit",
      keywords: ["card", "spade", "suit"], ru: ["масть", "пики"], uk: ["масть", "піки"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2667", name: "white club suit",
      keywords: ["card", "club", "suit"], ru: ["крести", "масть"], uk: ["масть", "хрести"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2663", name: "club suit",
      keywords: ["card", "club", "suit"], ru: ["крести", "масть"], uk: ["масть", "хрести"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u263A", name: "smiling face",
      keywords: ["face", "smile", "smiling", "text"], ru: ["смайлик", "улыбка"], uk: ["посмішка", "смайлик"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u263B", name: "black smiling face",
      keywords: ["face", "smile", "smiling"], ru: ["смайлик", "улыбка"], uk: ["посмішка", "смайлик"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2605", name: "black star",
      keywords: ["favorite", "star"], ru: ["звезда", "избранное"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2606", name: "white star",
      keywords: ["outline", "star"], ru: ["звезда", "контур"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2726", name: "black four pointed star",
      keywords: ["star"], ru: ["звезда"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2727", name: "white four pointed star",
      keywords: ["star"], ru: ["звезда"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2729", name: "stress outlined white star",
      keywords: ["star"], ru: ["звезда"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u272A", name: "circled white star",
      keywords: ["star"], ru: ["звезда"], uk: ["зірка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2190", name: "leftwards arrow",
      keywords: ["arrow", "left"], ru: ["влево", "стрелка"], uk: ["вліво", "стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2192", name: "rightwards arrow",
      keywords: ["arrow", "right"], ru: ["вправо", "стрелка"], uk: ["вправо", "стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2191", name: "upwards arrow",
      keywords: ["arrow", "up"], ru: ["вверх", "стрелка"], uk: ["вгору", "стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2193", name: "downwards arrow",
      keywords: ["arrow", "down"], ru: ["вниз", "стрелка"], uk: ["вниз", "стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2194", name: "left right arrow",
      keywords: ["arrow", "both"], ru: ["стрелка"], uk: ["стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2195", name: "up down arrow",
      keywords: ["arrow", "both"], ru: ["стрелка"], uk: ["стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u21D2", name: "rightwards double arrow",
      keywords: ["arrow", "double", "implies", "right"], ru: ["следовательно", "стрелка"], uk: ["стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u21D0", name: "leftwards double arrow",
      keywords: ["arrow", "double", "left"], ru: ["стрелка"], uk: ["стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u21D4", name: "left right double arrow",
      keywords: ["arrow", "double", "iff"], ru: ["стрелка"], uk: ["стрілка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2713", name: "check mark",
      keywords: ["check", "done", "ok", "tick", "yes"], ru: ["галочка", "готово", "да"], uk: ["галочка", "готово"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2714", name: "heavy check mark",
      keywords: ["check", "done", "ok", "tick"], ru: ["галочка", "готово"], uk: ["галочка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2717", name: "ballot x",
      keywords: ["cross", "no", "x"], ru: ["крестик", "нет"], uk: ["хрестик"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2718", name: "heavy ballot x",
      keywords: ["cross", "no", "x"], ru: ["крестик", "нет"], uk: ["хрестик"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2610", name: "ballot box",
      keywords: ["box", "checkbox", "empty"], ru: ["квадрат", "чекбокс"], uk: ["квадрат"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2611", name: "ballot box with check",
      keywords: ["box", "checked", "checkbox"], ru: ["галочка", "чекбокс"], uk: ["галочка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2612", name: "ballot box with x",
      keywords: ["box", "checked", "cross"], ru: ["крестик", "чекбокс"], uk: ["хрестик"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u266A", name: "eighth note",
      keywords: ["music", "note", "song"], ru: ["нота", "музыка"], uk: ["нота", "музика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u266B", name: "beamed eighth notes",
      keywords: ["music", "notes", "song"], ru: ["ноты", "музыка"], uk: ["ноти", "музика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2669", name: "quarter note",
      keywords: ["music", "note"], ru: ["нота", "музыка"], uk: ["нота", "музика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u266C", name: "beamed sixteenth notes",
      keywords: ["music", "notes"], ru: ["ноты", "музыка"], uk: ["ноти", "музика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2022", name: "bullet",
      keywords: ["dot", "point"], ru: ["точка", "буллит"], uk: ["точка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00B7", name: "middle dot",
      keywords: ["dot", "point"], ru: ["точка"], uk: ["точка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00B0", name: "degree sign",
      keywords: ["degree", "temperature"], ru: ["градус", "температура"], uk: ["градус"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00A7", name: "section sign",
      keywords: ["paragraph", "section"], ru: ["параграф", "секция"], uk: ["параграф"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00B6", name: "pilcrow",
      keywords: ["paragraph"], ru: ["абзац", "параграф"], uk: ["абзац"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2020", name: "dagger",
      keywords: ["footnote"], ru: ["сноска", "кинжал"], uk: ["примітка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2021", name: "double dagger",
      keywords: ["footnote"], ru: ["сноска"], uk: ["примітка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2116", name: "numero sign",
      keywords: ["number", "no"], ru: ["номер"], uk: ["номер"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00A9", name: "copyright sign",
      keywords: ["copyright", "c"], ru: ["копирайт", "права"], uk: ["копірайт"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00AE", name: "registered sign",
      keywords: ["registered", "r"], ru: ["зарегистрировано"], uk: ["зареєстровано"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2122", name: "trade mark sign",
      keywords: ["tm", "trademark"], ru: ["торговая марка"], uk: ["торгова марка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2026", name: "horizontal ellipsis",
      keywords: ["dots", "ellipsis"], ru: ["многоточие"], uk: ["багатокрапка"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00AB", name: "left-pointing double angle quotation mark",
      keywords: ["quote", "guillemet"], ru: ["кавычка"], uk: ["лапки"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00BB", name: "right-pointing double angle quotation mark",
      keywords: ["quote", "guillemet"], ru: ["кавычка"], uk: ["лапки"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u203D", name: "interrobang",
      keywords: ["question", "exclamation"], ru: ["вопрос", "восклицание"], uk: ["питання", "окличний"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2600", name: "black sun with rays",
      keywords: ["sun", "weather"], ru: ["солнце", "погода"], uk: ["сонце", "погода"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2601", name: "cloud",
      keywords: ["weather", "cloud"], ru: ["облако", "погода"], uk: ["хмара", "погода"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2602", name: "umbrella",
      keywords: ["rain", "umbrella", "weather"], ru: ["зонт", "дождь"], uk: ["зонт", "дощ"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2603", name: "snowman",
      keywords: ["snow", "winter"], ru: ["снеговик", "зима"], uk: ["сніговик", "зима"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u263D", name: "first quarter moon",
      keywords: ["moon"], ru: ["луна"], uk: ["місяць"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u263E", name: "last quarter moon",
      keywords: ["moon"], ru: ["луна"], uk: ["місяць"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u26A0", name: "warning sign",
      keywords: ["warning", "caution"], ru: ["внимание", "предупреждение"], uk: ["увага", "попередження"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2622", name: "radioactive sign",
      keywords: ["radioactive", "danger"], ru: ["радиация", "опасность"], uk: ["радіація", "небезпека"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u262F", name: "yin yang",
      keywords: ["balance", "tao"], ru: ["инь янь", "дао"], uk: ["інь ян", "дао"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u262E", name: "peace symbol",
      keywords: ["peace"], ru: ["мир", "пацифик"], uk: ["мир", "паціфік"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u270C", name: "victory hand",
      keywords: ["v", "victory"], ru: ["победа", "мир"], uk: ["перемога", "мир"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u20AC", name: "euro sign",
      keywords: ["euro", "money"], ru: ["евро", "деньги"], uk: ["євро", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00A3", name: "pound sign",
      keywords: ["gbp", "pound", "money"], ru: ["фунт", "деньги"], uk: ["фунт", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00A5", name: "yen sign",
      keywords: ["yen", "money"], ru: ["иена", "деньги"], uk: ["ієна", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00A2", name: "cent sign",
      keywords: ["cent", "money"], ru: ["цент", "деньги"], uk: ["цент", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u20B4", name: "hryvnia sign",
      keywords: ["hryvnia", "money", "uah"], ru: ["гривна", "деньги"], uk: ["гривня", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u20BD", name: "ruble sign",
      keywords: ["money", "ruble"], ru: ["рубль", "деньги"], uk: ["карбованець", "гроші"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00B1", name: "plus-minus sign",
      keywords: ["math", "plus", "minus"], ru: ["плюс минус", "математика"], uk: ["плюс мінус", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00D7", name: "multiplication sign",
      keywords: ["math", "times", "x"], ru: ["умножение", "математика"], uk: ["множення", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u00F7", name: "division sign",
      keywords: ["divide", "math"], ru: ["деление", "математика"], uk: ["ділення", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2248", name: "almost equal to",
      keywords: ["approx", "math"], ru: ["примерно", "математика"], uk: ["приблизно", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2260", name: "not equal to",
      keywords: ["math", "neq"], ru: ["не равно", "математика"], uk: ["не дорівнює", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2264", name: "less-than or equal to",
      keywords: ["math"], ru: ["меньше равно", "математика"], uk: ["менше рівно", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2265", name: "greater-than or equal to",
      keywords: ["math"], ru: ["больше равно", "математика"], uk: ["більше рівно", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u221E", name: "infinity",
      keywords: ["math", "infinity"], ru: ["бесконечность", "математика"], uk: ["нескінченність", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u221A", name: "square root",
      keywords: ["math", "root"], ru: ["корень", "математика"], uk: ["корінь", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2211", name: "n-ary summation",
      keywords: ["math", "sum"], ru: ["сумма", "математика"], uk: ["сума", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2205", name: "empty set",
      keywords: ["math", "null"], ru: ["пустое множество", "математика"], uk: ["порожня множина", "математика"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2648", name: "aries sign",
      keywords: ["zodiac", "sign"], ru: ["овен", "знак зодиака"], uk: ["овен", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2649", name: "taurus sign",
      keywords: ["zodiac", "sign"], ru: ["телец", "знак зодиака"], uk: ["телець", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264A", name: "gemini sign",
      keywords: ["zodiac", "sign"], ru: ["близнецы", "знак зодиака"], uk: ["близнюки", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264B", name: "cancer sign",
      keywords: ["zodiac", "sign"], ru: ["рак", "знак зодиака"], uk: ["рак", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264C", name: "leo sign",
      keywords: ["zodiac", "sign"], ru: ["лев", "знак зодиака"], uk: ["лев", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264D", name: "virgo sign",
      keywords: ["zodiac", "sign"], ru: ["дева", "знак зодиака"], uk: ["діва", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264E", name: "libra sign",
      keywords: ["zodiac", "sign"], ru: ["весы", "знак зодиака"], uk: ["терези", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u264F", name: "scorpius sign",
      keywords: ["zodiac", "sign"], ru: ["скорпион", "знак зодиака"], uk: ["скорпіон", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2650", name: "sagittarius sign",
      keywords: ["zodiac", "sign"], ru: ["стрелец", "знак зодиака"], uk: ["стрілець", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2651", name: "capricorn sign",
      keywords: ["zodiac", "sign"], ru: ["козерог", "знак зодиака"], uk: ["козоріг", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2652", name: "aquarius sign",
      keywords: ["zodiac", "sign"], ru: ["водолей", "знак зодиака"], uk: ["водолій", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2653", name: "pisces sign",
      keywords: ["zodiac", "sign"], ru: ["рыбы", "знак зодиака"], uk: ["риби", "знак зодіаку"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2654", name: "chess white king",
      keywords: ["chess", "figure"], ru: ["король"], uk: ["король"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2655", name: "chess white queen",
      keywords: ["chess", "figure"], ru: ["ферзь", "королева"], uk: ["королева"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2656", name: "chess white rook",
      keywords: ["chess", "figure"], ru: ["ладья"], uk: ["тура"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2657", name: "chess white bishop",
      keywords: ["chess", "figure"], ru: ["слон"], uk: ["офіцер"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2658", name: "chess white knight",
      keywords: ["chess", "figure"], ru: ["конь"], uk: ["кінь"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2659", name: "chess white pawn",
      keywords: ["chess", "figure"], ru: ["пешка"], uk: ["пішак"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265A", name: "chess black king",
      keywords: ["chess", "figure"], ru: ["король"], uk: ["король"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265B", name: "chess black queen",
      keywords: ["chess", "figure"], ru: ["ферзь", "королева"], uk: ["королева"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265C", name: "chess black rook",
      keywords: ["chess", "figure"], ru: ["ладья"], uk: ["тура"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265D", name: "chess black bishop",
      keywords: ["chess", "figure"], ru: ["слон"], uk: ["офіцер"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265E", name: "chess black knight",
      keywords: ["chess", "figure"], ru: ["конь"], uk: ["кінь"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u265F", name: "chess black pawn",
      keywords: ["chess", "figure"], ru: ["пешка"], uk: ["пішак"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2680", name: "die face-one",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "один"], uk: ["кубик", "кістка", "один"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2681", name: "die face-two",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "два"], uk: ["кубик", "кістка", "два"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2682", name: "die face-three",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "три"], uk: ["кубик", "кістка", "три"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2683", name: "die face-four",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "четыре"], uk: ["кубик", "кістка", "чотири"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2684", name: "die face-five",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "пять"], uk: ["кубик", "кістка", "п'ять"],
      group: GROUP, base: -1, variants: [] },
    { emoji: "\u2685", name: "die face-six",
      keywords: ["dice", "die"], ru: ["кубик", "кость", "шесть"], uk: ["кубик", "кістка", "шість"],
      group: GROUP, base: -1, variants: [] },
]

function entries() { return glyphs }

// Matching text, lowercased once at load — the catalogue's own
// discipline. A term matches when it appears in the name or any
// keyword list; the page concatenates these results beside the
// catalogue's ranked ones.
var matchNames = []
var matchAllKeywords = []
for (var i = 0; i < glyphs.length; i++) {
    matchNames.push(glyphs[i].name.toLowerCase())
    matchAllKeywords.push(
        lowerAll(glyphs[i].keywords)
            .concat(lowerAll(glyphs[i].ru))
            .concat(lowerAll(glyphs[i].uk)))
}

function lowerAll(words) {
    var lowered = []
    for (var w = 0; w < words.length; w++)
        lowered.push(words[w].toLowerCase())
    return lowered
}

function search(query) {
    var terms = String(query || "").toLowerCase().split(/\s+/)
        .filter(function (t) { return t !== "" })
    if (terms.length === 0) return []
    var out = []
    for (var i = 0; i < glyphs.length; i++) {
        var hit = true
        for (var t = 0; t < terms.length; t++) {
            var term = terms[t]
            var inName = matchNames[i].indexOf(term) !== -1
            var inWords = false
            for (var k = 0; k < matchAllKeywords[i].length; k++) {
                if (matchAllKeywords[i][k].indexOf(term) !== -1) {
                    inWords = true
                    break
                }
            }
            if (!inName && !inWords) { hit = false; break }
        }
        if (hit) out.push(glyphs[i])
    }
    return out
}
