#!/usr/bin/env bash
#
# Levels 5-8 probe entry point (ticket 20, first task). Run ONLY through the
# nested session, inside omarchy-vm:
#
#   cd ~/oskar && tools/nested-session.sh bash ~/lvl5-probe/run.sh
#
# Owns the helper process and the three probe legs (Chromium Wayland,
# Chromium X11, foot); the assertions and verdicts live in drive.py.
#
set -uo pipefail

probe_dir="$HOME/lvl5-probe"
runtime="${XDG_RUNTIME_DIR:-}"

if [[ "${OSK_NESTED_SESSION:-}" != "1" || -z "$runtime" ]]; then
    echo "Run this through: tools/nested-session.sh bash ~/lvl5-probe/run.sh" >&2
    exit 1
fi
if [[ ! -f "$probe_dir/make_keymap.py" || ! -x "$HOME/oskar/daemon/target/release/oskar-daemon" ]]; then
    echo "missing $probe_dir/make_keymap.py or the guest-built daemon" >&2
    exit 1
fi

cd "$probe_dir"
python3 make_keymap.py || exit 1

# Same first-run hygiene the smoke suite applies: the autogenerated nested
# config spawns hyprland-welcome, which maps a window in front of everything
# and would take the focus every leg waits for.
display="${WAYLAND_DISPLAY:-}"
if [[ -n "$display" ]]; then
    for pid in $(pgrep -f '[h]yprland-welcome' || true); do
        if tr '\0' '\n' < "/proc/$pid/environ" 2>/dev/null \
            | grep -qx "WAYLAND_DISPLAY=${display}"; then
            kill "$pid" 2>/dev/null || true
        fi
    done
fi
hyprctl dispatch closewindow class:hyprland-welcome >/dev/null 2>&1 || true

daemon="$HOME/oskar/daemon/target/release/oskar-daemon"
"$daemon" > "$runtime/osk-lvl5-probe.log" 2>&1 &
daemon_pid=$!
cleanup() {
    kill "$daemon_pid" 2>/dev/null || true
    pkill -f 'user-data-dir=/tmp/chromeprobe' 2>/dev/null || true
}
trap cleanup EXIT

socket="$runtime/oskar/control.sock"
for _ in $(seq 1 60); do
    [[ -S "$socket" ]] && break
    sleep 0.05
done
if [[ ! -S "$socket" ]]; then
    echo "helper socket did not appear; log:" >&2
    cat "$runtime/osk-lvl5-probe.log" >&2
    exit 1
fi

status=0
legs=("$@")
(( ${#legs[@]} == 0 )) && legs=(wayland x11 foot)
for leg in "${legs[@]}"; do
    case "$leg" in
    wayland|foot)
        python3 drive.py "$leg"; (( status |= $? ))
        ;;
    x11)
        python3 drive.py x11   # exit 3 = skipped (no nested XWayland); not a failure
        rc=$?; [[ "$rc" != 0 && "$rc" != 3 ]] && status=1
        ;;
    *)
        echo "unknown leg: $leg" >&2; exit 1
        ;;
    esac
done

echo "================ LEVELS 5-8 PROBE SUMMARY ================"
cat "$probe_dir"/result-*.txt 2>/dev/null
exit "$status"
