#!/usr/bin/env bash
# Emits the AUR-ready PKGBUILD for the current tag: the in-tree recipe with
# sha256sums=('SKIP') replaced by the REAL tarball checksum. Release-note
# checksums are documentation makepkg never enforces; the AUR copy must
# verify for real, and this builds it
# mechanically instead of by hand. Run AFTER the tag is pushed:
#   tools/make-aur-recipe.sh            # to stdout
#   tools/make-aur-recipe.sh out/PKGBUILD
set -euo pipefail
root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$root"
pkgver=$(sed -n 's/^pkgver=//p' PKGBUILD | head -1)
url=https://github.com/Vladkarok/oskar

archive=$(mktemp)
trap 'rm -f "$archive"' EXIT
curl -sfL --max-time 30 "$url/archive/refs/tags/v$pkgver.tar.gz" -o "$archive"
sum=$(sha256sum "$archive" | cut -d' ' -f1)

out=$(mktemp)
sed "s/^sha256sums=('SKIP')/sha256sums=('$sum')/" PKGBUILD >"$out"
if ! grep -q "^sha256sums=('$sum')$" "$out"; then
  echo "FAIL: the SKIP line was not where the recipe expects it — check PKGBUILD" >&2
  exit 1
fi
{
  cat "$out"
  printf '\n# AUR copy for v%s — generated by tools/make-aur-recipe.sh.\n' "$pkgver"
  printf '# The in-tree recipe keeps SKIP by design (decisions §61); this copy\n'
  printf '# verifies the tag tarball with the real checksum above.\n'
} >"${1:-/dev/stdout}"
rm -f "$out"
