#!/usr/bin/env bash
#
# Runs a command against a throwaway nested Hyprland instead of the session you
# are sitting in.
#
# This exists because of a real incident: a keymap feedback loop between the
# helper and the compositor produced 56,547 keymap rebuilds in five minutes,
# pegged xkbcomp, and froze the desktop badly enough to need a switch to a TTY.
# The daemon now has guards against that specific loop, but anything that drives
# a virtual keyboard can wedge a seat in a new way, so exercise it somewhere
# disposable first.
#
# Both the compositor and XDG_RUNTIME_DIR are private to the run, so the test
# daemon binds its own control socket and cannot collide with the live one.
#
#   tools/nested-session.sh daemon/target/release/omarchy-osk-daemon
#   tools/nested-session.sh foot   # sanity-check the nested session itself
#
set -uo pipefail

# A nested compositor still opens a window in its parent desktop. Default
# graphical tests to the VM; host use requires a deliberate manual override.
if [[ "${OSK_ALLOW_HOST_NESTED:-}" != "1" ]] \
    && ! systemd-detect-virt --vm --quiet 2>/dev/null; then
    echo "Graphical tests run in omarchy-vm. Host nested Hyprland is disabled; explicitly authorised manual runs may set OSK_ALLOW_HOST_NESTED=1." >&2
    exit 1
fi

if ! command -v Hyprland >/dev/null; then
    echo "Hyprland is not installed" >&2
    exit 1
fi

# Short path on purpose: Hyprland refuses its IPC socket when the directory
# name is long ("Socket2 path is too long"), and mktemp's default is already
# too long once the instance signature is appended.
workdir="/tmp/osk-nest.$$"
runtime="$workdir/rt"
mkdir -p "$runtime"
chmod 700 "$runtime"

cleanup() {
    local pids status=$?
    pids=$(jobs -p)
    [[ -n "$pids" ]] && kill $pids 2>/dev/null
    # A failed run keeps its workdir — compositor log included — because the
    # difference between a product fault and a flaky nested compositor is
    # exactly what that log says.
    if (( status == 0 )); then
        rm -rf "$workdir"
    else
        echo "--- workdir kept for inspection: $workdir" >&2
    fi
}
trap cleanup EXIT

# Lua rather than .conf: the old format raises a deprecation banner, and a
# nested compositor draws that banner on the screen you are working on.
cat > "$workdir/hypr.lua" <<'CONF'
hl.config({
  autogenerated = true,
  monitor = { "WL-1, 1280x800@60, 0x0, 1" },
  input = {
    kb_layout = "us,ua",
    kb_options = "grp:caps_toggle",
  },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
  },
  animations = { enabled = false },
})
CONF

host_runtime="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"

# A nested compositor is a Wayland client of the session that launched this
# script. An ssh shell carries no WAYLAND_DISPLAY, and libwayland's default
# (wayland-0) is not where this session publishes its socket — the nested
# Hyprland then dies in CBackend::create() before its own socket ever
# appears (measured 2026-09-09, ticket 20's levels-5-8 probe). Default to
# the live session's own display; a per-run override still wins.
if [[ -z "${WAYLAND_DISPLAY:-}" ]]; then
    for sock in "$host_runtime"/wayland-*; do
        [[ -S "$sock" ]] || continue
        WAYLAND_DISPLAY=${sock##*/}
        export WAYLAND_DISPLAY
        break
    done
fi

before=$(ls "$host_runtime"/wayland-* 2>/dev/null | grep -v '\.lock$' | sort)
# Snapshot the instance directories too — both sets are compared after
# launch, so both must be taken before it.
before_hypr=$(/bin/ls "$host_runtime/hypr" 2>/dev/null | sort)
# Same discipline for the X sockets: the live session's XWayland owns :0,
# and an X11 test client pointed at the wrong display maps a window on the
# desktop you are working in — exactly what this script exists to prevent.
before_x=$(/bin/ls /tmp/.X11-unix 2>/dev/null | sort)

# Take the socket snapshot before launch; a fast compositor can publish its
# socket before the next shell command and would otherwise become invisible to
# the set difference below. The signature is unset so Hyprland accepts a second
# instance. XDG_RUNTIME_DIR remains the host one because nested Hyprland is a
# Wayland client of the real session.
env -u HYPRLAND_INSTANCE_SIGNATURE \
    Hyprland -c "$workdir/hypr.lua" > "$workdir/hypr.log" 2>&1 &

for _ in $(seq 1 40); do
    after=$(ls "$host_runtime"/wayland-* 2>/dev/null | grep -v '\.lock$' | sort)
    display=$(comm -13 <(echo "$before") <(echo "$after") | head -1)
    [[ -n "$display" ]] && break
    sleep 0.5
done
display=$(basename "${display:-}")

if [[ -z "${display:-}" ]]; then
    echo "nested compositor did not come up; log follows" >&2
    tail -n 20 "$workdir/hypr.log" >&2
    exit 1
fi

# The command under test gets a private XDG_RUNTIME_DIR so its control socket
# cannot collide with the one the installed service already owns. The nested
# display and the nested Hyprland instance directory are linked in, so it can
# still reach the compositor and its event socket.
ln -sf "$host_runtime/$display" "$runtime/$display"

# Same set-difference discipline as the display above, for the same reason:
# "newest directory wins" is wrong the moment a stale instance directory
# outlives its compositor, and then every hyprctl call under test talks to
# the wrong (or a dead) instance while the window under test waits for a
# focus check that never looks at it.
signature=""
for _ in $(seq 1 20); do
    signature=$(comm -13 \
        <(echo "$before_hypr") \
        <(/bin/ls "$host_runtime/hypr" 2>/dev/null | sort) | head -1)
    [[ -n "$signature" ]] && break
    sleep 0.5
done

if [[ -n "$signature" ]]; then
    mkdir -p "$runtime/hypr"
    ln -sfn "$host_runtime/hypr/$signature" "$runtime/hypr/$signature"
fi

echo "nested compositor: $display  (instance $signature, private runtime $runtime)"
echo "--- running: $* ---"

# Hyprland spawns XWayland eagerly once it is up (observed: the new socket
# appears within the same seconds as the Wayland one). Wait briefly for it;
# if it never appears the X11 tests must refuse rather than fall back to
# the live display.
xdisplay=""
for _ in $(seq 1 20); do
    new_x=$(comm -13 <(echo "$before_x") <(/bin/ls /tmp/.X11-unix 2>/dev/null | sort) \
        | grep -v '_$' | head -1)
    [[ -n "$new_x" ]] && break
    sleep 0.5
done
if [[ -n "$new_x" ]]; then
    xdisplay=":${new_x#X}"
fi
echo "nested XWayland: ${xdisplay:-none}"

before_xkb=$(grep -c xkbcomp "$workdir/hypr.log" 2>/dev/null || true)

# The config is disposable along with the session, so the command under test
# may rewrite it and `hyprctl reload` — which is the only way to change a
# setting Hyprland applies to devices at config time, `hyprctl keyword` being
# refused outright by the Lua parser.
export OSK_NEST_CONFIG="$workdir/hypr.lua"
export OSK_NESTED_SESSION=1

WAYLAND_DISPLAY="$display" XDG_RUNTIME_DIR="$runtime" \
    HYPRLAND_INSTANCE_SIGNATURE="$signature" OSK_NEST_XDISPLAY="$xdisplay" "$@"
status=$?

# The cost of this class of bug lands in the compositor, not in the subject
# under test: a keymap churn loop shows up as xkbcomp rebuilds while the
# daemon's own log stays quiet. Counting here is what makes it visible.
#
# The counter is Hyprland's log lines mentioning xkbcomp, and Hyprland 0.56
# emits a PAIR for an ordinary keymap install. The ceiling is derived, not
# observed — a guard whose number came from "what we measured last time" is a
# guard that ratchets upward every time someone adds a test:
#
#   What is counted is the COMPOSITOR's rebuilds, so what has to be
#   enumerated is the changes to what the COMPOSITOR compiles — not every
#   helper install. A helper upload goes to its own virtual keyboard; the
#   compositor recompiles when the seat's keymap identity changes, which in
#   the nested session means startup and whatever the suite points
#   `input:kb_file` at. There is no panel here, so nothing else moves it.
#
#   The ordered seat identities are:
#     default us; us,ua,de; us,ua(pc105); us,ua(pc104); us,ua,de;
#     us,ua(pc105); us,us(variants); us,ua(capslock-cancel);
#     us,ua(normal); ua,ru; us,ua(normal).
#   That is 11 including startup. The Electron gate then changes the
#   compositor input identity empty -> published (its preceding clear is an
#   empty -> empty no-op). The §35 gate changes published -> empty -> published.
#   Those are 3 more: 14 possible identity changes in total.
#
#   14 possible identity changes x 2 lines = 28.
#
#   Ticket 06's custom-keymap test installs four more keymaps in the HELPER
#   (a kb_file rewritten twice and the restore), and deliberately adds nothing
#   here: those never reach the seat, which is the distinction this count
#   turns on. A run that starts counting them is a run where something began
#   re-pointing the compositor, and that is worth failing over.
#
# 34 allows one more pair for compositor startup variance. A feedback loop
# grows by dozens almost immediately — the incident above was 56,547 in five
# minutes — so 34 still fails closed on the churn this guard exists to catch.
#
# Re-derived 2026-09-10 at 16 identity changes: the shared-keymap leg
# (ticket 06) re-points the seat's kb_file and restores it, which reaches
# Xwayland where the old derivation counted nothing. Each Xwayland keymap
# load logs one xkbcomp ERROR-REPORT pair on this guest — Xwayland warns on
# the extended map whatever it compiles — and the typing legs pass, so the
# reports are warnings, not failures. 16 x 2 = 32, + 1 = 34.
#
# If this number has to move again, re-derive it: count the identity changes,
# not the maps.
#
# Re-derived 2026-09-10 for ticket 24's text-pick legs (foot delivery, x11cat
# delivery, and the §35 invariant across a pick). A `text` pick uploads the
# transient keymap and then the installed one back to the helper's own
# virtual keyboard: two seat keymap loads that change NO identity — the
# installed map ends where it started — but each costs one Xwayland
# ERROR-REPORT pair on this guest, measured in isolation (2 picks: baseline
# 4 lines, then 10, then 14). Five picks in the suite, so the uploads alone
# are 5 x 2 pairs x 2 lines = 20. Measured whole-suite costs wobble around
# that enumeration with the legs' focus choreography — 44 lines for three
# picks when the first two legs landed, 36 for three picks once the x11cat
# leg ran red at its first pick and the observer leg never started — so the
# allotment is 4 pairs per pick rather than the uploads alone:
#
#   32 (identity changes, unchanged above) + 5 picks x 4 pairs x 2 lines
#   = 40, + 2 (one startup-variance pair) = 74.
#
# Re-derived 2026-09-11 for the stage-C delivery legs. The suite now runs
# THIRTEEN picks: the two text legs of ticket 24's pick test, Electron's
# four text-unicode picks, the x11cat leg's two, the §35 leg's one, the
# isolation leg's text+text-unicode pair, the focus-split's one, and the
# mid-delivery stop's one (which uploads its entry map and, on the abort
# path, never restores — covered by its pick's allotment):
#
#   32 (identity changes, unchanged above) + 13 picks x 4 pairs x 2 lines
#   = 104, + 4 (the stop test's respawned helper: one startup upload and
#   one configure upload, two pairs) + 2 (one startup-variance pair)
#   = 142.
#
# Observed on this guest with the legs landed and green: 50 and 52 on the
# five-pick runs (earlier partial runs: 44 green at three picks, 36 red at
# the same point). A feedback loop
# grows at ~190 pairs per second (the incident above), so 138 still fails
# closed on the churn this guard exists to catch.
after_xkb=$(grep -c xkbcomp "$workdir/hypr.log" 2>/dev/null || true)
rebuilds=$((after_xkb - before_xkb))
echo "--- exited with $status; compositor keymap rebuilds during run: $rebuilds ---"
if (( rebuilds > 142 )); then
    echo "unsafe keymap churn detected" >&2
    exit 1
fi
exit $status
