#!/usr/bin/env bash
#
# Entry point for the control-socket integration seam. This script owns the
# helper process and nothing else; the assertions live in
# tools/integration/suite.py and the plumbing they use in harness.py.
#
# Needs a compositor: run in the VM under the nested session, never directly:
#
#   tools/nested-session.sh tools/smoke-daemon.sh
#
set -euo pipefail

# Refuse before any compositor query, process cleanup, or helper startup.
# This is an accidental-launch guard; nested-session.sh owns these values.
# The workdir pattern is nested-session.sh's mktemp (/tmp/osk-n.XXXXXX —
# the security audit's unpredictable-name finding); only the SHAPE is
# checked here, the session script is the authority.
nested_runtime="${XDG_RUNTIME_DIR:-}"
if [[ "${OSK_NESTED_SESSION:-}" != "1"
    || ! "$nested_runtime" =~ ^/tmp/osk-n\.[A-Za-z0-9]+/rt$
    || "${OSK_NEST_CONFIG:-}" != "${nested_runtime%/rt}/hypr.lua" ]]; then
    echo "Run this test in omarchy-vm via tools/nested-session.sh tools/smoke-daemon.sh." >&2
    exit 1
fi
if [[ ! -f "$OSK_NEST_CONFIG" || -z "${HYPRLAND_INSTANCE_SIGNATURE:-}"
    || -z "${WAYLAND_DISPLAY:-}" || ! -S "$XDG_RUNTIME_DIR/$WAYLAND_DISPLAY" ]]; then
    echo "Nested test environment is incomplete; refusing compositor access." >&2
    exit 1
fi

root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
daemon="$root/daemon/target/release/oskar-daemon"

# A binary older than the source it came from is the quietest way to spend a
# nested run proving nothing: the suite takes the prebuilt helper as it finds
# it, so a forgotten `cargo build --release` reports yesterday's behaviour
# under today's test names. Refuse rather than mislead.
if [[ -x "$daemon" ]]; then
  newest_source=$(find "$root/daemon/src" "$root/daemon/Cargo.toml" \
    "$root/daemon/Cargo.lock" -newer "$daemon" -print -quit 2>/dev/null)
  if [[ -n "$newest_source" ]]; then
    echo "The helper binary is older than $newest_source." >&2
    echo "Run: cargo build --release --manifest-path $root/daemon/Cargo.toml" >&2
    exit 1
  fi
fi
socket="$XDG_RUNTIME_DIR/oskar/control.sock"
log="$XDG_RUNTIME_DIR/oskar-smoke.log"

# Build the deliberately tiny public Wayland observer used by decisions §35's
# keymap-payload regression. Generated xdg-shell bindings stay in the private
# runtime directory; the repository carries only the readable test client.
observer_build="$XDG_RUNTIME_DIR/osk-keymap-observer-build"
observer="$observer_build/keymap-observer"
if ! command -v cc >/dev/null || ! command -v wayland-scanner >/dev/null \
    || ! command -v pkg-config >/dev/null \
    || ! pkg-config --exists wayland-client xkbcommon wayland-protocols; then
  echo "The nested suite needs cc, pkg-config, wayland-scanner, wayland-client, xkbcommon and wayland-protocols for the §35 observer." >&2
  exit 1
fi
xdg_shell_xml="$(pkg-config --variable=pkgdatadir wayland-protocols)/stable/xdg-shell/xdg-shell.xml"
if [[ ! -f "$xdg_shell_xml" ]]; then
  echo "The nested suite cannot find xdg-shell.xml at $xdg_shell_xml." >&2
  exit 1
fi
mkdir -p "$observer_build"
wayland-scanner client-header "$xdg_shell_xml" \
  "$observer_build/xdg-shell-client-protocol.h"
wayland-scanner private-code "$xdg_shell_xml" \
  "$observer_build/xdg-shell-protocol.c"
cc -std=c11 -Wall -Wextra -Werror \
  -I"$observer_build" \
  "$root/tools/integration/keymap-observer.c" \
  "$observer_build/xdg-shell-protocol.c" \
  $(pkg-config --cflags --libs wayland-client xkbcommon) \
  -o "$observer"
export OSK_KEYMAP_OBSERVER="$observer"

# The stuck-key cap ships at fifteen seconds (spec-v1 §6). A suite that slept
# through that four times over would be useless, so the helper takes the cap
# from the environment and the suite reads the same variable — what is asserted
# is the cap's behaviour, with its duration as the one injected fact.
export OSKAR_HOLD_CAP_MS="${OSKAR_HOLD_CAP_MS:-2000}"

# The helper must not start against a compositor whose config is still
# loading. Hyprland applies input:kb_layout to a keyboard when the device
# appears, and a keymap uploaded first freezes that bookkeeping in place
# (m_keymapOverridden) — a helper racing the config load ends up typing the
# right keymap under a devices JSON that says the built-in default. The
# session's own kb_layout being loaded is the start signal.
for _ in $(seq 1 100); do
  layout=$(hyprctl getoption input:kb_layout 2>/dev/null | sed -n 's/^str: //p')
  [[ "$layout" == "us,ua" ]] && break
  sleep 0.1
done
if [[ "$layout" != "us,ua" ]]; then
  echo "nested compositor never loaded input:kb_layout = us,ua" >&2
  exit 1
fi

# The autogenerated config makes Hyprland spawn its first-run welcome app,
# which maps a window in front of everything and takes the focus the typing
# assertions need. It has done its one job the moment the session exists.
# Isolated to this nested compositor: comm is 15 chars so `pkill -x
# hyprland-welcome` matches nothing (and a global pkill would also hit
# the live session). Filter by this WAYLAND_DISPLAY; closewindow is the
# same compositor's own client list.
display="${WAYLAND_DISPLAY:-}"
if [[ -n "$display" ]]; then
  for pid in $(pgrep -f '[h]yprland-welcome' || true); do
    if tr '\0' '\n' < "/proc/$pid/environ" 2>/dev/null \
        | grep -qx "WAYLAND_DISPLAY=${display}"; then
      kill "$pid" 2>/dev/null || true
    fi
  done
fi
hyprctl dispatch closewindow class:hyprland-welcome >/dev/null 2>&1 || true

"$daemon" >"$log" 2>&1 &
daemon_pid=$!
cleanup() {
  kill "$daemon_pid" 2>/dev/null || true
  wait "$daemon_pid" 2>/dev/null || true
}
trap cleanup EXIT
trap 'echo "--- helper log ---" >&2; cat "$log" >&2' ERR

for _ in $(seq 1 50); do
  [[ -S "$socket" ]] && break
  sleep 0.05
done
if [[ ! -S "$socket" ]]; then
  echo "helper socket did not appear" >&2
  echo "--- helper log ---" >&2
  cat "$log" >&2 || true
  exit 1
fi

python3 "$root/tools/integration/suite.py" "$socket" "$log" "$daemon_pid"

echo "nested helper integration suite passed"
